spring:
  application:
    name: micro-customer-account
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      import-check:
        enabled: true
      enabled: true
      label: main
server:
  port: 8085